mutation UpdateIssue($id: String!, $title: String, $description: String, $stateId: String, $assigneeId: String, $priority: Float, $estimate: Float) {
  issueUpdate(id: $id, input: { title: $title, description: $description, stateId: $stateId, assigneeId: $assigneeId, priority: $priority, estimate: $estimate }) {
    success
    issue {
      id
      identifier
      title
      description
      url
      priority
      estimate
      assignee {
        id
        name
      }
      state {
        id
        name
      }
    }
  }
}
