packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  "@biomejs/biome": true
  esbuild: true
  isolated-vm: true
  lefthook: true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - pg-boss@12.18.3
  - fumadocs-core@16.10.0
  - fumadocs-mdx@15.0.12
  - fumadocs-ui@16.10.0
