import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { SITE_URL } from "@tulipfarm/constants/site";
import { PackDefinitionSchema } from "@tulipfarm/schema";

export const PACK_SCHEMA_PATH = "schemas/pack/v1.schema.json";

export function renderPackSchema(): string {
  return `${JSON.stringify(
    {
      ...PackDefinitionSchema,
      $schema: "https://json-schema.org/draft/2020-12/schema",
      $id: `${SITE_URL}/${PACK_SCHEMA_PATH}`,
      title: "TulipFarm Pack v1",
      description:
        "An adaptable collection of asset templates and a dependency Plan. " +
        "Importing previews the Pack; installation requires an adapted plan and confirmation.",
      $comment:
        "Generated from packages/schema/src/pack.ts. Do not edit this file; run " +
        "pnpm --filter @tulipfarm/www generate:pack-schema.",
    },
    null,
    2
  )}\n`;
}

export function generatePackSchema(): void {
  const destination = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "../public",
    PACK_SCHEMA_PATH
  );
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, renderPackSchema());
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  generatePackSchema();
}
