import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { SITE_URL } from "@tulipfarm/constants/site";
import { PlanDefinitionSchema } from "@tulipfarm/schema";

export const PLAN_SCHEMA_PATH = "schemas/plan/v1.schema.json";

export function renderPlanSchema(): string {
  return `${JSON.stringify(
    {
      ...PlanDefinitionSchema,
      $schema: "https://json-schema.org/draft/2020-12/schema",
      $id: `${SITE_URL}/${PLAN_SCHEMA_PATH}`,
      title: "TulipFarm YAML Plan v1",
      description:
        "A dependency plan containing exact Tool calls, Agent sub-prompts, and child Routines. " +
        "Use plan_compile to validate dependency cycles, references, and execution semantics.",
      $comment:
        "Generated from packages/schema/src/plan.ts. Do not edit this file; run " +
        "pnpm --filter @tulipfarm/www generate:plan-schema.",
    },
    null,
    2
  )}\n`;
}

export function generatePlanSchema(): void {
  const destination = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "../public",
    PLAN_SCHEMA_PATH
  );
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, renderPlanSchema());
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  generatePlanSchema();
}
