import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { deriveModelProfiles, type LlmConfig } from "@tulipfarm/schema";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as stringifyYaml } from "yaml";
import { derivedModelProfileId } from "../model-profile-documents";
import { removeGeneratedModelFiles } from "./002-remove-model-files";

const TMP = join(import.meta.dirname, "__remove_model_files_tmp__");
const CONFIG = {
  tiers: {
    quick: { providers: [{ provider: "openai", model: "gpt-fast" }] },
    standard: { providers: [{ provider: "openai", model: "gpt-balanced" }] },
    complex: { providers: [{ provider: "openai", model: "gpt-thorough" }] },
  },
} satisfies LlmConfig;

async function writeGeneratedProfiles(): Promise<void> {
  await mkdir(join(TMP, "models"), { recursive: true });
  for (const profile of deriveModelProfiles(CONFIG)) {
    const { profileId, spec, ...profileSpec } = profile;
    await writeFile(
      join(TMP, "models", `${profileId}.yaml`),
      stringifyYaml({
        apiVersion: "tulipfarm.ai/v1",
        kind: "ModelProfile",
        metadata: {
          id: derivedModelProfileId(profileId),
          slug: profileId,
          schemaVersion: 1,
          authoredVersion: 1,
          lifecycle: "draft",
        },
        spec: profileSpec,
      }),
      "utf8"
    );
  }
}

beforeEach(() => mkdir(TMP, { recursive: true }));
afterEach(() => rm(TMP, { recursive: true, force: true }));

describe("removeGeneratedModelFiles", () => {
  it("removes the complete retired directory when every file has the v1 fingerprint", async () => {
    await writeGeneratedProfiles();

    await removeGeneratedModelFiles(TMP);

    await expect(readdir(join(TMP, "models"))).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("no-ops when the retired directory is absent", async () => {
    await expect(removeGeneratedModelFiles(TMP)).resolves.toBeUndefined();
  });

  it("refuses atomically when a profile was not generated by v1", async () => {
    await writeGeneratedProfiles();
    const customPath = join(TMP, "models", "custom.yaml");
    await writeFile(customPath, "kind: ModelProfile\n", "utf8");

    await expect(removeGeneratedModelFiles(TMP)).rejects.toThrow("non-generated profile");
    expect(await readFile(customPath, "utf8")).toContain("ModelProfile");
    expect((await readdir(join(TMP, "models"))).length).toBeGreaterThan(1);
  });

  it("refuses nested or unrelated content instead of recursively erasing it", async () => {
    await writeGeneratedProfiles();
    await mkdir(join(TMP, "models", "archive"));

    await expect(removeGeneratedModelFiles(TMP)).rejects.toThrow("unrecognized entry");
    expect(await readdir(join(TMP, "models"))).toContain("archive");
  });
});
