export {
  DEFAULT_CONFIRMATION_TTL_MS,
  InMemoryPendingMemoryStore,
  type PendingMemory,
  type PendingMemoryStore,
  type ResolvePendingRequest,
  type ResolvePendingResult,
  resolvePendingMemory,
} from "./confirm";
export {
  isContradictionCandidate,
  type MemoryContradictionInput,
  type MemoryContradictionPort,
  normalizeSubject,
  type ResolveContradictionsResult,
  resolveContradictions,
} from "./contradiction";
export {
  authorizeMemoryEpisode,
  MEMORY_EPISODE_CHUNK_TYPES,
  MEMORY_EPISODE_SOURCE_TYPES,
  type MemoryEpisode,
  type MemoryEpisodeChunk,
  type MemoryEpisodeChunkType,
  type MemoryEpisodeProvenance,
  type MemoryEpisodeSource,
  type MemoryEpisodeSourceType,
  type MemoryEpisodeStore,
  type MemoryEpisodeWriteResult,
} from "./episode";
export {
  type CandidateRejectionReason,
  type CandidateScreening,
  isImperativeStatement,
  MAX_CANDIDATE_STATEMENT_CHARS,
  MAX_CANDIDATE_SUBJECT_CHARS,
  type MemoryCandidate,
  type MemoryCandidateScreen,
  type MemoryExtractionInput,
  type MemoryExtractionPort,
  MIN_CANDIDATE_CONFIDENCE,
  type ProposeCandidatesRequest,
  type ProposeCandidatesResult,
  type ProposedCandidate,
  proposeMemoryCandidates,
  type RejectedCandidate,
  screenMemoryCandidate,
} from "./extract";
export {
  commitAssertion,
  type EraseResult,
  eraseMemory,
  type ForgetRequest,
  type ForgetResult,
  forgetMemory,
  InMemoryMemoryStore,
  MEMORY_TRUST_TIERS,
  MEMORY_TYPES,
  type MemoryAssertion,
  type MemoryAuditSink,
  type MemoryConfirmationState,
  type MemoryDeps,
  type MemoryEraseCounts,
  type MemoryEraseStoreCounts,
  type MemoryEvidenceAuthorizationPort,
  type MemoryEvidenceRef,
  type MemoryOrigin,
  type MemoryProvenance,
  type MemoryScopeFilter,
  type MemorySettingsView,
  type MemoryStatus,
  type MemoryStore,
  type MemoryTrustTier,
  type MemoryType,
  matchesScopeFilter,
  memorySettingsView,
  type ProceduralCorrectionRequest,
  type RememberDenialReason,
  type RememberRequest,
  type RememberResult,
  rememberMemory,
  rememberProceduralCorrection,
} from "./memory";
export {
  DEFAULT_HALF_LIFE_DAYS,
  DEFAULT_IMPORTANCE_WEIGHT,
  fuseMemoryCandidates,
  importanceWeight,
  type MemoryCandidateSignals,
  type MemoryRankingOptions,
  type RankedMemoryAssertion,
  RRF_K,
  rankMemoryCandidates,
  recencyWeight,
} from "./rank";
export {
  type MemoryExclusion,
  type MemoryExclusionReason,
  type MemoryRecallIndex,
  type MemoryRecallIndexRequest,
  type RecallRequest,
  type RecallResult,
  recallMemory,
} from "./retrieve";
export {
  authorizeMemoryScope,
  type MemoryScopeDecision,
  type MemoryScopeDenialReason,
  type MemoryScopeRequest,
  type MemoryScopeTarget,
} from "./scope";
export {
  endMemorySpan,
  MEMORY_METRICS,
  MEMORY_SPANS,
  type MemoryTelemetryAttributes,
  type MemoryTelemetryPort,
  recordMemoryCounter,
  recordMemoryGauge,
  recordMemoryHistogram,
  recordMemorySpanError,
  safeMemoryAttributes,
  setMemorySpanAttributes,
  startMemorySpan,
} from "./telemetry";
