export {
  createRecord,
  deleteRecord,
  previewRecordDelete,
  type ResourceBeforeHook,
  ResourceBeforeHookError,
  type ResourceCatalog,
  type ResourceDefinition,
  type ResourceDeletePlan,
  ResourceDeletePlanLimitError,
  type ResourceDeletePlanRecord,
  type ResourceDoc,
  type ResourceRepo,
  type ResourceRepoFactory,
  ResourceUniqueViolationError,
  type ResourceWriteError,
  type ResourceWritePorts,
  type ResourceWriteResult,
  updateRecord,
} from "./service";
